### ISSUE TITLE
Missing src/qt/htmlcoin-qt or GUI

### ISSUE THREAD

**Issue by hutber** [HTMLCOIN/HTML5#14]
This issue tracker is only for technical issues related to Qtum.

#### If so, please list the steps to reproduce below:
1. Run all commands successfully from 64-bit linux guide
2. Navigate to `HTMLCOIN/src/qt`
3. Cannot find `htmlcoin-qt`

### Expected behaviour
Be able to run the Gui `htmlcoin-qt`

### Screenshots.
![image](https://user-images.githubusercontent.com/1344898/34504041-cf5b3cce-f013-11e7-86e9-3385b66f6cac.png)

### What version of Qtum are you using?
commit 68e07e8c7094d95129cd24bd7de51bc8a7afdb57
Author: Peter Bushnell <bushsolo@gmail.com>
Date:   Mon Jan 1 14:26:07 2018 +0000

    v2.0.0.3

### Machine specs:
- OS: Ubuntu 16.04

### Any extra information that might be useful in the debugging process.
[buildlog.txt](https://github.com/HTMLCOIN/HTML5/files/1599011/buildlog.txt)
t or a link to a pastebin type site are preferred.

**Comment by Bushstar** [comment]
If using system libs did you install the dependencies for Qt?

It might be simpler to use compile and use the dependencies in the depends folder as it comes with everything you need including Qt libs.

**Linux 64bit**
```
git clone https://github.com/HTMLCOIN/HTMLCOIN.git
cd HTMLCOIN/
cd depends/
make HOST=x86_64-pc-linux-gnu
cd ..
rm -Rf src/cpp-ethereum/
git submodule update --init --recursive
./autogen.sh
./configure --prefix=`pwd`/depends/x86_64-pc-linux-gnu --without-gui --without-miniupnpc
make clean
make
```

**Linux 32bit**
```
git clone https://github.com/HTMLCOIN/HTMLCOIN.git
cd HTMLCOIN/
cd depends/
make HOST=i686-pc-linux-gnu
cd ..
rm -Rf src/cpp-ethereum/
git submodule update --init --recursive
./autogen.sh
./configure --prefix=`pwd`/depends/i686-pc-linux-gnu --without-gui --without-miniupnpc
make clean
make
```

**Comment by asos-hutber** [comment]
Thanks @Bushstar I re-ran all the commands again and finally ended up with this error in my terminal, sorry if I'm missing some fundimental here

```
~/HTMLCOIN $ make
 cd . && /bin/bash /home/hutber/Crypto/HTMLCoin/HTMLCOIN/build-aux/missing automake-1.15 --foreign
/bin/bash: /home/hutber/Crypto/HTMLCoin/HTMLCOIN/build-aux/missing: No such file or directory
Makefile:598: recipe for target 'Makefile.in' failed
make: *** [Makefile.in] Error 1
```

**Comment by Bushstar** [comment]
I just double check the command above and configure did not display the single quotes around pwd properly, I've now added code formatting to preserve the commands. 

Make sure that you have all required tool for building.

`sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils`

Looks like some files are missing, if you run ./autogen.sh it should recreate them but make sure that you have the installed software from above and are running configure with the pwd command as shown in the instructions.

**Comment by hutber** [comment]
Ok perfect, thanks very much. 

I have go all steps to complete without any issues I do believe. However I still can't find `htmlcoin-qt` anywhere?
