### ISSUE TITLE
Change the README

### ISSUE THREAD

**Issue by azrin619** [HTMLCOIN/HTML5#7]
Readme is old
New locations etc need to be rewritten

**Comment by HTMLCOIN** [comment]
Please send the links, I will update.


All the best,

*HTMLCOIN TEAM*


*The “crypto currency model” is done by consensus.
<http://www.htmlcoin.com>*

**Comment by zrsmith75** [comment]
README has been updated.

**Comment by zrsmith75** [comment]
Added
